- api/routes/search_routes/search_datasource_route.py
- api/services/datasource_services/search_datasets_by_terms.py
- requirements.txt
- tests/test_search_datasource.py
This pull request resolves the issue where the `/search` endpoint fails when the `keys` parameter contains square brackets (`[]`) or other Solr-reserved characters. By escaping these characters before constructing the Solr query, the `400 Bad Request` error is avoided.
**Main Changes:**
- Implemented the `escape_solr_special_chars` function to escape Solr-reserved characters.
- Applied character escaping to `terms` and `keys` before building the Solr query string.
- Updated test cases to verify the correct handling of special characters in `keys`.
**Effects:**
- Prevents Solr syntax errors when `keys` contain square brackets (`[]`) or other special characters.
- Preserves existing functionality for normal `terms` and `keys`.
**How to Test:**
1. Run the unit and integration tests.
2. Call …
> fix: Escape special characters in keys parameter to prevent Solr syntax errors

- README.md
- api/config/__init__.py
- api/config/swagger_settings.py
- api/routes/default_routes/get.py
- api/services/default_services/index.py
- api/templates/index.html
- env_variables/example.env_swagger
This Pull Request resolves the issue by introducing an optional JupyterLab integration into the POP API. The following changes were made:
- Added new environment variables in `env_variables/.env_swagger`:
- `USE_JUPYTERLAB`: Enables or disables the JupyterLab integration (`True`/`False`).
- `JUPYTER_URL`: Specifies the URL of the JupyterLab instance.
- Updated `swagger_settings.py` to load and manage the new environment variables.
- Modified the `/` endpoint to:
- Check if JupyterLab integration is enabled.
- Pass `use_jupyterlab` and `jupyter_url` to the template context.
- Updated `index.html` to display a styled link to JupyterLab when integration is enabled.
- Added documentation in the README under the **Optional Integrations** section to describe the new functionality.
> feat: Add JupyterLab integration with optional configuration

- api/routes/register_routes/post_kafka.py
- api/services/kafka_services/add_kafka.py
- tests/test_create_kafka_datasource.py
This pull request addresses the issue of duplicate dataset registration in the Kafka endpoint. The following changes have been implemented:
1. **Enhanced Error Handling**: 
- Added logic to handle cases where a dataset with the same name or URL already exists.
- The API now returns a `409 Conflict` response with a clear message indicating the dataset duplication.
2. **Tests for Duplicity**:
- Created a test to verify that duplicate dataset registration returns the expected `409 Conflict` response.
- Confirmed existing tests still pass.
3. **Updated Documentation**:
- The Swagger documentation now includes details about the `409 Conflict` response and an example message for duplicate datasets.
> fix: Improve error handling for duplicate dataset registration

- api/config/ckan_settings.py
- api/config/swagger_settings.py
- api/main.py
- api/routes/status_routes/get.py
- api/services/default_services/index.py
- api/services/status_services/__init__.py
- api/services/status_services/check_api_status.py
- api/services/status_services/check_ckan_status.py
- api/templates/index.html
- env_variables/example.env_ckan
- env_variables/example.env_swagger
- tests/test_create_kafka_datasource.py
- tests/test_create_organization.py
- tests/test_create_s3_resource.py
- tests/test_create_url_resource.py
- tests/test_delete_organization.py
- tests/test_update_kafka_datasource.py
**Summary of Changes**
- Added a new `CKAN_LOCAL_ENABLED` variable in `.env_ckan` to make local CKAN optional.
- Updated route inclusion logic so endpoints for CKAN-based features are only mounted if `CKAN_LOCAL_ENABLED` is `True`.
- Refactored the status checks to provide both local and global CKAN reachability info, and updated the index template to display these statuses.
- Introduced new styling across the dashboard (Local CKAN, Kafka, JupyterLab) to keep a consistent Bootstrap card layout.
- Implemented `pytest.skipif` logic and route existence checks to skip tests when local CKAN is disabled or relevant endpoints are not mounted, avoiding unnecessary 404/405 failures.
- Ran `flake8` to ensure code cleanliness and consistency.
> feat: make local CKAN optional, refine dashboard styling, and conditionally skip tests

- api/services/datasource_services/search_datasets_by_terms.py
- tests/test_search_datasource.py
- Improved error handling when server='global' and the CKAN global instance is unreachable.
- Replaced technical error messages with a user-friendly "Global catalog is not reachable.".
- Fixed import issue in test_search_datasource.py (HTTPException now correctly imported from fastapi).
- Updated tests to correctly assert the expected behavior and ensure the mock function is properly awaited.
> Fix: Ensure global CKAN errors return user-friendly message

- api/config/ckan_settings.py
- api/routes/search_routes/list_organizations_route.py
- api/services/organization_services/list_organization.py
- tests/test_list_organization.py
This pull request updates the /organization route to use 'global' 
as the default server and provides more user-friendly error handling 
when pre_ckan is not configured or accessible:
- Changes the default server parameter from 'local' to 'global'.
- Updates existing tests in test_list_organization.py to expect 'global' 
by default instead of 'local'.
- Uses a custom error message if the CKAN connection fails with 
"No scheme supplied" for pre_ckan, indicating that the server 
is not configured or unreachable.
- Adds a patch for pre_ckan_enabled in the pre_ckan test to 
ensure a 200 response when pre_ckan is enabled.
This ensures consistent behavior for the default server and 
provides clearer feedback when pre_ckan cannot be reached.
> feat: set default server to 'global' and improve pre_ckan error handling

- api/models/searchrequest_model.py
- api/routes/search_routes/post_search_datasource_route.py
- api/services/datasource_services/search_datasource.py
- tests/test_search_datasource_post.py
**Overview**  
This pull request updates the test_search_datasource_post.py suite 
so that it expects "global" as the default server value instead of "local." 
Previously, the test asserted that the server would default to "local," 
which caused a mismatch with the actual implementation where 
"global" is the default.
**Changes**  
- Modified test_search_datasource_exception to expect 'server="global"' 
when the server parameter is not specified in the request.
- Removed references to 'local' as the default server in the test. 
- Ensured that the test aligns with the current behavior of 
the POST /search endpoint.
**Impact**  
- No breaking changes; simply aligns existing tests with 
the actual default server logic.
- Increases clarity and consistency across the test suite.
**Testing** …
> fix: update test_search_datasource_post to use 'global' as the default server

- api/routes/register_routes/post_kafka.py
**Overview**  
This pull request adds the ability to select the CKAN server (local or 
pre_ckan) via a query parameter (?server=...) in the POST /kafka endpoint, 
defaulting to local if none is provided. It also resolves a minor text 
mismatch in the duplicate dataset error message to align with the 
existing test expectations.
**Changes**  
1. Introduced an optional `server` query parameter (local or pre_ckan) 
to the POST /kafka endpoint.  
2. Defaulted to 'local' when the query parameter is omitted.  
3. Added friendly error handling for 'pre_ckan' when `pre_ckan_enabled` 
is False or the pre_ckan URL lacks a valid scheme.  
4. Corrected the duplicate dataset error message to match 
"A dataset with the given name or URL already exists." as expected 
by the test suite.
**Impact**  
- …
> feat: add query param server selection for POST /kafka and fix duplicate error message

- api/routes/register_routes/post_s3.py
- api/services/s3_services/add_s3.py
**Overview**  
This pull request adds a `?server=` query parameter to the POST /s3 
endpoint, allowing clients to choose between 'local' or 'pre_ckan' 
for S3 resource creation. If no server is specified, the route 
defaults to 'local'.
**Changes**  
1. Introduced an optional query parameter, server (local/pre_ckan), 
with 'local' as the default.  
2. If server=pre_ckan is requested but pre_ckan_enabled=False, 
a 400 error is returned with a clear message.  
3. If the pre_ckan URL has no valid scheme, a friendly 
"Pre-CKAN server is not configured or unreachable." error is 
raised.  
4. Maintained backward compatibility for calls that do not provide 
a server parameter.
**Impact**  
- Users can explicitly target a local or pre_ckan CKAN instance 
when creating S3 resources.  
- Clear …
> feat: add optional server query param to POST /s3 for local or pre_ckan

- api/routes/register_routes/post_url.py
This pull request introduces an optional `server` query parameter 
to the POST /url endpoint, allowing users to specify either 'local' 
or 'pre_ckan'. If no server is provided, the endpoint defaults to 'local'.
**Changes**  
1. Accepts `?server=local` or `?server=pre_ckan` in the POST /url route.  
2. If `server=pre_ckan` is used but `pre_ckan_enabled` is False, 
a 400 error is returned with a clear message.  
3. If the pre_ckan URL lacks a valid scheme, a friendly 
"Pre-CKAN server is not configured or unreachable." error is shown.  
4. Maintains backward compatibility by defaulting to `local` when no 
server parameter is given.
**Impact**  
- Allows explicit selection of the CKAN instance for URL resources.  
- Returns user-friendly errors if pre_ckan is disabled or misconfigured.  
- …
> feat: add optional query param server to POST /url for local or pre_ckan

- api/routes/update_routes/put_url.py
- api/services/url_services/update_url.py
**Overview**  
This pull request adds an optional server query parameter to the 
PUT /url/{resource_id} endpoint, allowing users to specify whether they 
want to update the resource in the local CKAN instance or in the 
pre-CKAN instance. If no server parameter is provided, the endpoint 
defaults to 'local' to maintain backward compatibility.
**Changes**  
1. Introduced a `ckan_instance` parameter in `update_url` to avoid 
relying solely on ckan_settings.ckan.  
2. Added ?server=local or ?server=pre_ckan to the PUT /url/{resource_id} 
route.  
3. Returns a 400 error if pre_ckan is disabled (`pre_ckan_enabled=False`) 
or if the pre_ckan URL is missing a valid scheme ("No scheme supplied").  
4. Preserves existing behavior when the server parameter is not specified, 
defaulting to local …
> feat: add optional ?server=local/pre_ckan query param to PUT /url/{resource_id}

- api/routes/update_routes/put_s3.py
- api/services/s3_services/update_s3.py
**Overview**  
This pull request introduces an optional server query parameter to the 
PUT /s3/{resource_id} endpoint, allowing users to specify whether they 
want to update the S3 resource in a local CKAN instance or a pre-CKAN 
instance. By default, if no server is provided, the route continues to 
use the local CKAN.
**Changes**  
1. Added a `ckan_instance` parameter to the `update_s3` function so it 
no longer relies solely on ckan_settings.ckan.  
2. Implemented ?server=local or ?server=pre_ckan in the PUT /s3/{resource_id} 
route, returning a 400 error if pre_ckan is disabled or lacks a valid 
URL scheme.  
3. Preserved backward compatibility for calls that do not specify any 
server parameter.
**Impact**  
- Users can explicitly select which CKAN instance (local or pre_ckan) 
to …
> feat: add optional ?server=local/pre_ckan query param to PUT /s3/{resource_id}

- api/routes/delete_routes/delete_organization_route.py
- api/services/organization_services/delete_organization.py
- tests/test_delete_organization.py
This pull request adds an optional server query parameter to the 
DELETE /organization/{organization_name} endpoint, allowing users 
to delete organizations from either the local CKAN or a pre-CKAN instance. 
It also aligns the test suite with the new behavior, including the 
404 status code for non-existent organizations.
**Changes**  
1. Added a ckan_instance parameter in delete_organization to avoid relying 
solely on ckan_settings.ckan.  
2. Implemented ?server=local or ?server=pre_ckan in the DELETE /organization 
route.  
3. Returns a 400 error if pre_ckan is disabled or missing a valid URL scheme.  
4. Returns 404 if the organization does not exist.  
5. Updated tests/test_delete_organization.py to:
- Use ANY to ignore the ckan_instance parameter.  
- Expect a 404 status code for …
> feat: add optional ?server=local/pre_ckan to DELETE /organization/{organization_name}

- api/routes/delete_routes/delete_dataset.py
- api/services/dataset_services/delete_dataset.py
**Overview**  
This pull request introduces an optional server query parameter 
to the DELETE /resource and DELETE /resource/{resource_name} endpoints, 
allowing users to specify whether they want to delete the dataset 
in the local CKAN instance or in the pre-CKAN instance. If no server 
parameter is provided, the endpoints default to local CKAN.
**Changes**  
1. Added a ckan_instance parameter to the delete_dataset function 
so it no longer relies solely on ckan_settings.ckan.  
2. Implemented ?server=local or ?server=pre_ckan in both DELETE /resource 
and DELETE /resource/{resource_name} routes.  
3. Returns a 400 error if pre_ckan is disabled or if the pre_ckan URL 
lacks a valid scheme.  
4. Returns a 404 if the resource is not found.  
5. Maintains backward compatibility by …
> feat: add optional ?server=local/pre_ckan to DELETE /resource and /resource/{resource_name}

- api/services/keycloak_services/get_current_user.py
- tests/test_kafka_datasource_registration_and_search.py
Adds an integration test to verify Kafka dataset registration and its subsequent availability through the search endpoint.
- New integration test ensuring dataset creation endpoint (`/kafka`) works correctly with subsequent search validation.
Closes #48
> fix: Kafka registration and search integration test (#48)

- api/config/swagger_settings.py
- tests/test_kafka_datasource_registration_and_search.py
Ensures that `swagger_version` is fixed to "x.x.x" by excluding it from environment variables.
- Set swagger_version as fixed using `exclude=True` in Field from Pydantic.
- Updated default swagger_version to "x.x.x".
- Ensures version consistency and prevents accidental overrides from the environment.
Closes #50.
> fix: Fix swagger_version as constant in settings

- api/routes/register_routes/post_organization.py
- api/services/organization_services/create_organization.py
- tests/test_create_organization.py
This PR addresses issue #52 by adding an optional `server` parameter (`local`|`pre_ckan`) to the `/organization` endpoint, aligning it with the existing logic used in other endpoints (e.g., `/kafka`).
- Updated `create_organization` service to accept a `server` parameter.
- Updated `/organization` endpoint to handle optional `server` query parameter.
- Adjusted existing tests to include the new `server` parameter.
- All existing tests updated and passing.
> fix: Add optional 'server' param to /organization route (#52)

- api/config/swagger_settings.py
- api/main.py
- api/models/__init__.py
- api/models/request_kafka_model.py
- api/models/system_metrics_model.py
- api/services/status_services/__init__.py
- api/services/status_services/system_metrics.py
- api/tasks/metrics_task.py
- requirements.txt
This PR implements hourly logging of system metrics, addressing issue #54.
Metrics logged every hour include:
- Public IP address of the API server.
- CPU usage percentage.
- Memory usage percentage.
- Disk usage percentage.
- Added `psutil`, `requests`, and `fastapi-utils` dependencies.
- Created a new Pydantic model (`SystemMetrics`) to structure logged metrics.
- Added background task to log system metrics hourly.
- Configured FastAPI lifespan event to manage the background metrics task.
- Included logging configuration to store metrics information.
Closes #54
> feat: Implement hourly metrics logging (#54)

- api/config/swagger_settings.py
- api/routes/search_routes/search_datasource_route.py
- docker-compose.yml
- pytest.ini
- tests/test_kafka_datasource_registration_and_search.py
- tests/test_search_datasource.py
This pull request resolves issue #61 by rejecting the unsupported `'pre_ckan'` option in the `/search` endpoint. Additionally, it includes improvements to testing stability and configuration:
- Reject `'pre_ckan'` server option with clear error message (`400 Bad Request`)
- Update test assertions to reflect updated allowed server values
- Skip Kafka integration test when external CKAN certificate verification fails
- Suppress asyncio fixture scope warning by configuring `pytest.ini`
- Minor `flake8` cleanup to ensure PEP8 compliance
Closes #61
> [fix] Disallow 'pre_ckan' in search endpoint and improve test stability

- .gitignore
- api/main.py
- docker-compose.yml
This PR implements issue #63 by configuring the logging system to persist  
metrics from `record_system_metrics()` into a rotating file `logs/metrics.log`.
- Replaced `logging.basicConfig` with `RotatingFileHandler` setup  
- Created a `logs/` directory if it does not exist  
- Logs are now written both to stdout and to `logs/metrics.log`  
- Log file rotates at 5MB, keeping 3 backups  
- Updated `docker-compose.yml` to mount the logs folder for persistence
---
Closes #63
> [Feature] Persist system metrics to log file

- api/config/dxspaces_settings.py
- api/config/keycloak_settings.py
- api/tasks/metrics_task.py
This PR implements issue #65 by enhancing the system metrics logs with  
structured information from active services. Each service now includes its  
URL or host/port in a consistent JSON format.
Additionally, new `enabled` flags were added to control which services are  
included in the logs:
- `keycloak_enabled` (default: True)
- `dxspaces_enabled` (default: True)
- Added `keycloak_enabled` and `dxspaces_enabled` settings  
- Structured service entries (e.g., `{"url": ...}`) for:
- Keycloak  
- DXSpaces  
- JupyterLab  
- CKAN  
- Pre-CKAN  
- Services are logged only if explicitly enabled
---
Closes #65
> [Task] Include service URLs and flags in system metrics logs

- api/config/swagger_settings.py
- api/routes/default_routes/__init__.py
- api/services/default_services/index.py
- api/templates/index.html
This PR resolves #69 by integrating DXSpaces (data staging) into the dashboard interface, similar to the existing JupyterHub integration.
- New configuration flags `use_dxspaces` and `dxspaces_url` in `swagger_settings.py`.
- Context passed from backend to template includes DXSpaces configuration.
- Dashboard now conditionally displays a DXSpaces card, linking to the configured DXSpaces URL.
> [Feature] Expose DXSpaces integration in dashboard (#69)

- api/config/swagger_settings.py
This PR updates the default metrics_endpoint in swagger_settings.py from http://fed-api/metrics/ to http://federation.ndp.utah.edu/metrics/ to reflect the correct endpoint for the federation setup. It also changes the env_file path from ./env_variables/.env_swagger to .env for consistency with the rest of the application configuration.
Closes #75.
> Update default metrics_endpoint and env_file path

- api/routes/register_routes/post_kafka.py
- api/routes/register_routes/post_s3.py
- api/routes/register_routes/post_url.py
- api/services/status_services/check_api_status.py
- api/services/validation_services/validate_preckan_fields.py
- tests/test_create_kafka_datasource.py
- tests/test_kafka_datasource_registration_and_search.py
This PR implements strict validation of required CKAN fields when sending metadata to the `pre_ckan` server. It introduces a new utility function, `validate_preckan_fields()`, which inspects the incoming payload for all fields defined in the NDP Metadata Schema. Nested fields (e.g., `extras:uploadType`, `resource:name`) are supported via colon notation.
Closes: #77
> Fix #77: Validate Required CKAN Fields Before Resource Creation

- api/tasks/metrics_task.py
Por supuesto Raúl. Aquí la tienes:
---
```
feat: Include swagger_version in system metrics payload
```
This PR resolves issue #79 by including the API version (`swagger_version`)
in the system metrics payload sent to the metrics endpoint.
* Added `version` field to the `metrics_payload` in `metrics_task.py`.
* Updated the function docstring to document the new field.
* Included an example of the updated payload in the code comments.
1. Start the API with `public` set to `True` in your `.env` file.
2. Check the logs and verify that the `version` field appears in the JSON.
3. Ensure that the payload sent to `metrics_endpoint` includes the `version`.
```json
{
"public_ip": "1.2.3.4",
"cpu": "15%",
"memory": "65%",
"disk": "70%",
"version": "0.6.0",
"services": { ... }
}
```
Closes #79
> feat: Include swagger_version in system metrics payload

- api/models/urlrequest_model.py
- api/services/url_services/add_url.py
- Replaced FileTypeEnum with a plain string to support custom file types
- Updated processing validation to apply only for known built-in types (CSV, JSON, etc.)
- Skipped validation for unknown/custom file types to improve flexibility
> feat: allow custom file types in URLRequest model

- api/main.py
- api/models/update_dataset_model.py
- api/routes/update_routes/put_dataset.py
- api/services/dataset_services/general_dataset.py
- api/services/url_services/update_dataset.py
- api/services/url_services/update_url.py
- other/test_patch_resources_issue.py
- other/test_patch_resources_issue_fixed.py
PATCH `/dataset/{id}` was replacing all existing resources instead of adding new ones, making it behave identically to PUT.
**Before:** PATCH replaced all resources (incorrect)  
**After:** PATCH adds new resources to existing ones (correct)
Fixes #92
- Modified `patch_general_dataset()` in `api/services/dataset_services/general_dataset.py`
- Resources are now merged instead of replaced during PATCH operations
- Existing resources are preserved and new ones are added
- PUT behavior unchanged (still replaces all resources)
```bash
Initial resources: 1 → Final resources: 1 ❌ (replaced)
Initial resources: 1 → Final resources: 2 ✅ (added)
```
```json
{
"resources": [{"url": "new.json", "name": "new_resource"}]
}
```
Result: Adds to existing resources ✅
```json
{
"resources": [{"url": …
```
> Fix: PATCH endpoint replacing resources instead of adding them
